[build]
  command = "npm install"
  publish = "."  # Raíz del sitio estático
  functions = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"
  GITHUB_TOKEN = "TU_TOKEN_GITHUB"
  REPO_OWNER = "TU_USUARIO_O_ORGANIZACION"
  REPO_NAME = "NOMBRE_DEL_REPOSITORIO"

[dev]
  functions = "netlify/functions"
  targetPort = 8888

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"
